from django.urls import path

from Newspaper.views import (
    index,
    ArticlesListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    RedactorsListView,
    RedactorCreateView,
    RedactorDeleteView,
    RedactorDetailView,
    RedactorUpdateView,
    TopicsListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    toggle_assign_to_article,
)

urlpatterns = [
    path("", index, name="index"),

    path("redactors/",
         RedactorsListView.as_view(),
         name="redactors-list"),
    path("redactors/<int:pk>/",
         RedactorDetailView.as_view(),
         name="redactor-detail"),
    path("redactors/create/",
         RedactorCreateView.as_view(),
         name="redactor-create"),
    path("redactors/<int:pk>/year/",
         RedactorUpdateView.as_view(),
         name="redactor-update"),
    path("redactors/<int:pk>/delete/",
         RedactorDeleteView.as_view(),
         name="redactor-delete"),

    path("articles/",
         ArticlesListView.as_view(),
         name="articles-list"),
    path("articles/<int:rand_num>/<int:pk>/",
         ArticleDetailView.as_view(),
         name="article-detail"),
    path("articles/create/",
         ArticleCreateView.as_view(),
         name="article-create"),
    path("articles/<int:pk>/update/",
         ArticleUpdateView.as_view(),
         name="article-update"),
    path("articles/<int:pk>/delete/",
         ArticleDeleteView.as_view(),
         name="article-delete"),
    path("articles/<int:rand_num>/<int:pk>/toggle-assign/",
         toggle_assign_to_article,
         name="toggle-article-assign",),

    path("topics/",
         TopicsListView.as_view(),
         name="topics-list"),
    path("topics/create/",
         TopicCreateView.as_view(),
         name="topic-create"),
    path("topics/<int:pk>/update/",
         TopicUpdateView.as_view(),
         name="topic-update"),
    path("topics/<int:pk>/delete/",
         TopicDeleteView.as_view(),
         name="topic-delete"),
]

app_name = "newspaper"
