# Generated by Django 4.1 on 2024-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
